<a href="https://colab.research.google.com/github/eliseev-mk/lab2_emk/blob/main/Numpy_Exercise_copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Упражнения

Теперь, когда мы узнали о NumPy, давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы более сложные вопросы.

#### Импорт NumPy как np

In [1]:
import numpy as np

#### Создание массива из 10 нулей

In [3]:
zeros = np.zeros(10)
print("Массив из 10 нулей:\n", zeros)

Массив из 10 нулей:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Создайте массив из 10 единиц

In [4]:
ones = np.ones(10)
print("Массив из 10 единиц:\n", ones)

Массив из 10 единиц:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Создайте массив из 10 пятерок

In [5]:
fives = np.full(10, 5)
print("Массив из 10 пятерок:\n", fives)

Массив из 10 пятерок:
 [5 5 5 5 5 5 5 5 5 5]


#### Создадим массив целых чисел от 10 до 50

In [6]:
arr_10_to_50 = np.arange(10, 51)
print("Массив от 10 до 50:\n", arr_10_to_50)

Массив от 10 до 50:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Создадим массив из всех четных целых чисел от 10 до 50

In [7]:
even_10_to_50 = np.arange(10, 51, 2)
print("Чётные числа от 10 до 50:\n", even_10_to_50)

Чётные числа от 10 до 50:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Создание матрицы 3x3 со значениями в диапазоне от 0 до 8¶

In [8]:
mat_3x3 = np.arange(9).reshape(3, 3)
print("Матрица 3x3 от 0 до 8:\n", mat_3x3)

Матрица 3x3 от 0 до 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Создание единичной матрицы 3x3

In [9]:
identity_3x3 = np.eye(3)
print("Единичная матрица 3x3:\n", identity_3x3)

Единичная матрица 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Используйте NumPy для генерации случайного числа от 0 до 1

In [10]:
rand_num = np.random.rand()
print("Случайное число от 0 до 1:\n", rand_num)

Случайное число от 0 до 1:
 0.7526434095118612


#### Используйте NumPy для создания массива из 25 случайных чисел, отобранных из стандартного нормального распределения

In [11]:
rand_normal = np.random.randn(25)
print("25 чисел из N(0,1):\n", rand_normal)

25 чисел из N(0,1):
 [ 1.99201091  0.17130596  0.58421577  0.87881949 -0.42863207  0.59433153
  1.83451951 -1.85698081  0.43654066  1.69891525  0.40999676  0.69785213
  0.24665686 -0.41017533  0.20020369 -0.39093182  1.98496621 -0.224783
 -0.41584073 -0.00893052  0.20036771  0.90347    -0.64787707 -0.71652918
  0.9120711 ]


#### Создайте матрицу 10 на 10 из равномерно удаленных точек от 0.1 до 1( см linspace):

In [12]:
mat_10x10 = np.linspace(0.1, 1, 100).reshape(10, 10)
print("Матрица 10x10 от 0.1 до 1:\n", mat_10x10)

Матрица 10x10 от 0.1 до 1:
 [[0.1        0.10909091 0.11818182 0.12727273 0.13636364 0.14545455
  0.15454545 0.16363636 0.17272727 0.18181818]
 [0.19090909 0.2        0.20909091 0.21818182 0.22727273 0.23636364
  0.24545455 0.25454545 0.26363636 0.27272727]
 [0.28181818 0.29090909 0.3        0.30909091 0.31818182 0.32727273
  0.33636364 0.34545455 0.35454545 0.36363636]
 [0.37272727 0.38181818 0.39090909 0.4        0.40909091 0.41818182
  0.42727273 0.43636364 0.44545455 0.45454545]
 [0.46363636 0.47272727 0.48181818 0.49090909 0.5        0.50909091
  0.51818182 0.52727273 0.53636364 0.54545455]
 [0.55454545 0.56363636 0.57272727 0.58181818 0.59090909 0.6
  0.60909091 0.61818182 0.62727273 0.63636364]
 [0.64545455 0.65454545 0.66363636 0.67272727 0.68181818 0.69090909
  0.7        0.70909091 0.71818182 0.72727273]
 [0.73636364 0.74545455 0.75454545 0.76363636 0.77272727 0.78181818
  0.79090909 0.8        0.80909091 0.81818182]
 [0.82727273 0.83636364 0.84545455 0.85454545 0.86363636 0.

#### Создайте массив из 20 линейно удаленных точек от 0 до 1( см linspace):

In [13]:
linspace_20 = np.linspace(0, 1, 20)
print("20 точек от 0 до 1:\n", linspace_20)

20 точек от 0 до 1:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Индексы

В матрице

In [14]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Напишите код таким образом, чтоб появился вывод на экран

In [ ]:
# выведите

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# впишите код



In [ ]:
# выведите

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# впишите код



In [ ]:
# выведите

20

In [ ]:
# впишите код



In [ ]:
# выведите

20

In [ ]:
# впишите код
# отличный от кода выше



In [ ]:
# выведите

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# впишите код




In [ ]:
# выведите

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# впишите код




In [ ]:
# выведите

array([[21, 22, 23, 24, 25]])

In [ ]:
# впишите код




In [ ]:
# выведите

array([21, 22, 23, 24, 25])

In [ ]:
# впишите код




In [ ]:
# выведите

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# впишите код






In [ ]:
# выведите

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# впишите код





### Теперь сделайте следующее

#### Получить сумму всех значений в mat

In [15]:
mat = mat_10x10
total_sum = np.sum(mat)
print("Сумма всех значений в mat:\n", total_sum)

Сумма всех значений в mat:
 55.00000000000001


#### Получить стандартное отклонение значений в mat (пакет Статистика)

In [16]:
std_dev = np.std(mat)
print("Стандартное отклонение в mat:\n", std_dev)

Стандартное отклонение в mat:
 0.2624188186156556


#### Посчитайте сумму всех столбцов в mat

In [17]:
sum_columns = np.sum(mat, axis=0)
print("Сумма по столбцам:\n", sum_columns)

Сумма по столбцам:
 [5.09090909 5.18181818 5.27272727 5.36363636 5.45454545 5.54545455
 5.63636364 5.72727273 5.81818182 5.90909091]
